import test from 'node:test';import assert from 'node:assert/strict';import vm from 'node:vm';import {readFileSync} from 'node:fs';import {createHash,createHmac,randomUUID} from 'node:crypto';
class Sheet{constructor(name){this.name=name;this.cells=new Map();this.notes=new Map();this.maxRows=50;this.maxCols=26}getRange(r,c,n=1,w=1){const sheet=this;const range={getValues:()=>Array.from({length:n},(_,i)=>Array.from({length:w},(_,j)=>sheet.cells.get(`${r+i},${c+j}`)??'')),getNotes:()=>Array.from({length:n},(_,i)=>Array.from({length:w},(_,j)=>sheet.notes.get(`${r+i},${c+j}`)??'')),getDisplayValues:()=>range.getValues().map(row=>row.map(String)),getValue:()=>range.getValues()[0][0],getNote:()=>range.getNotes()[0][0],setValue:v=>range.setValues([[v]]),setValues:rows=>{rows.forEach((row,i)=>row.forEach((v,j)=>sheet.cells.set(`${r+i},${c+j}`,v)));return range},setNote:v=>{sheet.notes.set(`${r},${c}`,v);return range},setNumberFormat:()=>range};return range}getLastRow(){return Math.max(0,...[...this.cells.keys()].map(k=>Number(k.split(',')[0])))}getMaxRows(){return this.maxRows}getMaxColumns(){return this.maxCols}appendRow(row){this.getRange(this.getLastRow()+1,1,1,row.length).setValues([row])}hideSheet(){}getSheetId(){return 211}}
function setup(){const sheets=new Map(['人員設定','標案設定','案件001'].map(name=>[name,new Sheet(name)]));const book={getSheetByName:n=>sheets.get(n),insertSheet:n=>{const s=new Sheet(n);sheets.set(n,s);return s}};sheets.get('標案設定').getRange(5,1,1,3).setValues([['案件001','案件一','進行中']]);sheets.get('人員設定').getRange(6,1).setValue('阿林').setNote('ankuan-person:lin-id');const context=vm.createContext({Date,JSON,Number,String,Set,Error,Utilities:{getUuid:randomUUID,DigestAlgorithm:{SHA_256:'sha256'},computeDigest:(_,s)=>[...createHash('sha256').update(s).digest()],computeHmacSha256Signature:(s,key)=>[...createHmac('sha256',key).update(s).digest()]},SpreadsheetApp:{flush:()=>{}}});vm.runInContext(readFileSync(new URL('../google-apps-script/Code.gs',import.meta.url),'utf8'),context);return{context,book,sheets}}
const actor={id:'google-sub',nickname:'Jack',email:'jack@example.com',role:'admin'},data={id:'unique-transaction-001',project:'案件001',payerId:'lin-id',type:'expense',amount:500,date:'2026-01-01',desc:'交通費',category:'交通住宿',payment:'現金',note:'',photos:[]};
test('a retried write creates one ledger entry and one durable index',()=>{const {context,book,sheets}=setup();context.saveEntry_(book,data,actor,{});context.saveEntry_(book,data,actor,{});const ledger=sheets.get('案件001');assert.equal(ledger.getRange(13,2).getValue(),'阿林');assert.equal(ledger.getRange(13,6).getValue(),500);assert.equal(ledger.getRange(14,1).getValue(),'');assert.equal(sheets.get('_網站交易索引').getLastRow(),2);const note=JSON.parse(ledger.getRange(13,1).getNote());assert.equal(note.recorder,'Jack');assert.equal(note.payerId,'lin-id');});
test('reusing transaction id with different amount is rejected',()=>{const {context,book}=setup();context.saveEntry_(book,data,actor,{});assert.throws(()=>context.saveEntry_(book,{...data,amount:999},actor,{}),/交易編號已存在/)});
test('cell note carries the transaction identity when a complete input row is sorted',()=>{const {context,book,sheets}=setup();context.saveEntry_(book,data,actor,{});const sheet=sheets.get('案件001'),values=sheet.getRange(13,1,1,10).getValues(),note=sheet.getRange(13,1).getNote();sheet.getRange(14,1,1,10).setValues(values);sheet.getRange(14,1).setNote(note);sheet.getRange(13,1,1,10).setValues([Array(10).fill('')]);sheet.getRange(13,1).setNote('');assert.equal(context.findLedgerRow_(sheet,data.id),14)});
test('unsigned bridge calls are rejected',()=>{const {context}=setup();assert.throws(()=>context.verifyRequest_({ts:Date.now(),nonce:'x'.repeat(32),payload:'e30=',signature:'bad'},'a'.repeat(64)),/未通過/)});
test('shared access needs the exact long key',()=>{const {context}=setup();const key='k'.repeat(48);assert.doesNotThrow(()=>context.verifyPublicAccess_(key,key));assert.throws(()=>context.verifyPublicAccess_('wrong',key),/共用連結已失效/);assert.throws(()=>context.verifyPublicAccess_(key,''),/共用連結已失效/)});
test('receipt folders use the stable project id and visible project name',()=>{const {context,book}=setup();assert.equal(context.projectFolderName_(book,'案件001'),'案件001｜案件一')});
